#include "LimitOrderBook.h"
#include <iostream>
using namespace std;

int main() {
    LimitOrderBook lob;
    vector<Trade> trades;

    // Example sequence:
    // 1) Add some resting sell orders
    lob.insertLimitOrder(false, 10100, 50, trades); // sell @ 101.00, qty 50
    lob.insertLimitOrder(false, 10200, 30, trades); // sell @ 102.00

    // 2) Incoming buy that crosses the book
    OrderId buyId = lob.insertLimitOrder(true, 10200, 60, trades); // buy @ 102.00 qty 60
    // trades vector contains trades produced by the insertion (some seller ids unknown placeholder)
    cout << "Trades generated by buy order:\n";
    for (auto &t : trades) {
        OrderId buyer, seller; Price price; Quantity q;
        tie(buyer, seller, price, q) = t;
        cout << "BUYER=" << buyer << " SELLER=" << seller
                  << " PRICE=" << price << " QTY=" << q << "\n";
    }

    // Print book to inspect resting orders after matching
    lob.printBook();

    return 0;
}
